### ISSUE TITLE
Callback function signatures not following best practice of "error-first"

### ISSUE THREAD

**Issue by deldrid1** [electricimp/AzureIoTHub#25]
Refer to http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/.  In my opinion, "error-first" callbacks are the appropriate pattern and are worth making a major release of the class over.

[retrieveTwinProperties(onRetrieved)](https://github.com/electricimp/AzureIoTHub#callback-onretrievederror-reportedprops-desiredprops) follows this pattern with its `error, reportedProps, desiredProps` signature.  All of the callbacks that only take a single parameter of `error` obviously do too.

However, 2 callbacks are offenders...  
- The [onUpdated](https://github.com/electricimp/AzureIoTHub#callback-onupdatedprops-error) callback signature for [client.updateTwinProperties](https://github.com/electricimp/AzureIoTHub#updatetwinpropertiesprops-onupdated) uses `onUpdated(**props**, error)` instead of being `onUpdated(error, props)`
- The [onSent](https://github.com/electricimp/AzureIoTHub#callback-onsentmessage-error) callback signature for [client.sendMessage](https://github.com/electricimp/AzureIoTHub#sendmessagemessage-onsent) is also inverted

Its a minor code/documentation effort for the library and since the libraries are versioned it seems like something that should be considered?  Thoughts?

**Comment by alexey-nbl** [comment]
Yes, make sense to update to "error-first"
